apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-react-deployment
spec:
  selector:
    matchLabels:
      app: docker-react
  template:
    metadata:
      labels:
        app: docker-react
    spec:
      containers:
      - name: docker-react
        image: 705191013/react_image
---
  apiVersion: v1
  kind: Service
  metadata:
    name: docker-react-service
  spec:
    type: NodePort
    selector:
      app: docker-react
    ports:
      - name: docker-react
        port: 3000
        targetPort: 3000  
  #sercanyzz

